# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

input {
    accel_profile = flat
    force_no_accel = true
    kb_layout = us,lt
    kb_options = grp:alt_shift_toggle
    repeat_delay = 350
}
