# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# Workspace 3 apps
windowrule = match:class ^(steam)$, match:title ^(Friends List)$, workspace 3
windowrule = match:class ^(discord)$, workspace 3

# TTC Client (system wine)
windowrule = match:class ^(client.exe)$, match:title ^(Tamriel Trade Centre Client)$, float on
windowrule = match:class ^(client.exe)$, match:title ^(Tamriel Trade Centre Client)$, center on

# Force Steam and games to HDMI monitor
# windowrule = match:class ^(steam_app_.*)$, monitor HDMI-A-1
# windowrule = match:class ^(steam_app_.*)$, fullscreen on
# windowrule = match:class ^(steam_app_.*)$, immediate on


