# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# Workspace 3 apps
rule = workspace 3: class:^(steam)$, title:^(Friends List)$
rule = workspace 3: class:^(discord)$

# TTC Client (system wine)
rule = float,center: class:^(client.exe)$, title:^(Tamriel Trade Centre Client)$

# Force Steam and games to HDMI monitor
# rule = monitor:HDMI-A-1: class:^(steam_app_.*)$
# rule = fullscreen: class:^(steam_app_.*)$
# rule = immediate: class:^(steam_app_.*)$


